<Project Sdk="Godot.NET.Sdk/4.4.1">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <LangVersion>11.0</LangVersion>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <Folder Include="addons\"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="gdUnit4.analyzers" Version="1.0.0-rc7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0"/>
        <PackageReference Include="gdUnit4.api" Version="5.0.0-rc3"/>
        <PackageReference Include="gdUnit4.test.adapter" Version="3.0.0-rc1"/>
        <PackageReference Update="GodotSharp" Version="4.5.0-dev.5"/>
        <PackageReference Update="Godot.SourceGenerators" Version="4.5.0-dev.5"/>
        <PackageReference Include="NSubstitute" Version="5.3.0"/>
        <PackageReference Include="NSubstitute.Analyzers.CSharp" Version="1.0.17">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>