using System.Collections.Generic;
using CardCleaner.Scripts.Features.Worldgen.AutoTiling.Transitions;
using Godot;

namespace CardCleaner.Scripts.Features.Worldgen.AutoTiling;

/// <summary>
/// Resolves terrain transitions using the compiled transition map.
/// Loads the transition_map.json generated by the atlas compiler
/// and provides O(1) lookups for terrain transition coordinates.
/// </summary>
public class CompiledTransitionResolver : ITransitionResolver
{
    private const string DefaultTransitionMapPath = "res://Data/CompiledAtlas/transition_map.json";
    private const int DefaultCompiledAtlasSourceId = 0;

    private readonly CompiledTransitionMap _transitionMap;
    private readonly int _compiledAtlasSourceId;

    /// <summary>
    /// Gets the source ID for the compiled atlas.
    /// </summary>
    public int CompiledAtlasSourceId => _compiledAtlasSourceId;

    /// <summary>
    /// Creates a resolver with the default transition map path.
    /// </summary>
    public CompiledTransitionResolver() : this(DefaultTransitionMapPath, DefaultCompiledAtlasSourceId)
    {
    }

    /// <summary>
    /// Creates a resolver with a custom transition map path.
    /// </summary>
    /// <param name="transitionMapPath">Path to the transition_map.json file.</param>
    /// <param name="compiledAtlasSourceId">Source ID for the compiled atlas in the TileSet.</param>
    public CompiledTransitionResolver(string transitionMapPath, int compiledAtlasSourceId)
    {
        _compiledAtlasSourceId = compiledAtlasSourceId;
        _transitionMap = TransitionMapLoader.Load(transitionMapPath);
    }

    /// <summary>
    /// Resolves the atlas coordinates for a terrain transition.
    /// Returns the first variant (deterministic behavior).
    /// Note: Input bitmask is Full8 format, converted to Corner16 for transition map lookup.
    /// </summary>
    public Vector2I? ResolveTransition(string innerTerrainId, string outerTerrainId, int bitmask)
    {
        // Bitmask is already in Corner16 format from dual-grid (NE=1, SE=2, SW=4, NW=8)
        // Transition map uses Corner16 indexing, so use directly

        // Try direct lookup first (for fixed transitions and composited tiles)
        var coords = _transitionMap.GetVariantCoords(innerTerrainId, outerTerrainId, bitmask);
        if (coords.HasValue)
            return coords;

        // Try with border tile ID format: "{inner}_border"
        var borderId = $"{innerTerrainId}_border";
        coords = _transitionMap.GetVariantCoords(borderId, outerTerrainId, bitmask);
        if (coords.HasValue)
            return coords;

        // No transition found
        return null;
    }

    /// <summary>Resolves transition coordinates with deterministic position-based variant selection.</summary>
    public Vector2I? ResolveTransitionWithVariant(
        string innerTerrainId,
        string outerTerrainId,
        int bitmask,
        int x,
        int y)
    {
        // Bitmask is already in Corner16 format from dual-grid

        // Create position-based seed for deterministic random selection
        var positionSeed = HashPosition(x, y);

        // Try direct lookup first (for fixed transitions and composited tiles)
        var coords = _transitionMap.GetVariantCoordsWithRandom(innerTerrainId, outerTerrainId, bitmask, positionSeed);
        if (coords.HasValue)
            return coords;

        // Try with border tile ID format: "{inner}_border"
        var borderId = $"{innerTerrainId}_border";
        coords = _transitionMap.GetVariantCoordsWithRandom(borderId, outerTerrainId, bitmask, positionSeed);
        if (coords.HasValue)
            return coords;

        // No transition found
        return null;
    }

    /// <summary>
    /// Creates a stable hash from x,y coordinates for variant selection seeding.
    /// </summary>
    private static int HashPosition(int x, int y)
    {
        // Simple hash combining x and y that produces good distribution
        unchecked
        {
            var hash = 17;
            hash = hash * 31 + x;
            hash = hash * 31 + y;
            return hash;
        }
    }

    /// <summary>
    /// Resolves a transition with full render info, including fallback to provided coordinates.
    /// Uses first variant (deterministic behavior).
    /// When using compiled atlas, ensures fallback always uses sourceId 0.
    /// Note: Input bitmask is Full8 format, converted to Corner16 for transition map lookup.
    /// </summary>
    public TransitionResolveResult ResolveWithFallback(
        string innerTerrainId,
        string outerTerrainId,
        int bitmask,
        int fallbackSourceId,
        Vector2I fallbackCoords)
    {
        var coords = ResolveTransition(innerTerrainId, outerTerrainId, bitmask);
        return ResolveOrFallback(coords, innerTerrainId, bitmask, fallbackSourceId, fallbackCoords);
    }

    /// <summary>
    /// Resolves a transition with full render info and random variant selection.
    /// Uses position-based seeding for consistent re-renders.
    /// When using compiled atlas, ensures fallback always uses sourceId 0.
    /// Note: Input bitmask is Full8 format, converted to Corner16 for transition map lookup.
    /// </summary>
    public TransitionResolveResult ResolveWithFallbackAndVariant(
        string innerTerrainId,
        string outerTerrainId,
        int bitmask,
        int fallbackSourceId,
        Vector2I fallbackCoords,
        int tileX,
        int tileY)
    {
        var coords = ResolveTransitionWithVariant(innerTerrainId, outerTerrainId, bitmask, tileX, tileY);
        return ResolveOrFallback(coords, innerTerrainId, bitmask, fallbackSourceId, fallbackCoords);
    }

    private TransitionResolveResult ResolveOrFallback(
        Vector2I? primaryCoords,
        string innerTerrainId,
        int bitmask,
        int fallbackSourceId,
        Vector2I fallbackCoords)
    {
        if (primaryCoords.HasValue)
            return new TransitionResolveResult(_compiledAtlasSourceId, primaryCoords.Value);

        // Try to find ANY transition with this inner terrain to get valid compiled atlas coords
        var anyVariant = ResolveAnyVariant(innerTerrainId, bitmask);
        if (anyVariant.HasValue)
            return new TransitionResolveResult(_compiledAtlasSourceId, anyVariant.Value);

        // Ultimate fallback: if fallbackSourceId matches compiled atlas, use it
        if (fallbackSourceId == _compiledAtlasSourceId)
            return new TransitionResolveResult(fallbackSourceId, fallbackCoords);

        // Can't find valid coords - return error marker position (atlas 0,0 is typically valid)
        return new TransitionResolveResult(_compiledAtlasSourceId, Vector2I.Zero);
    }

    /// <summary>
    /// Checks if a transition exists for the given terrain pair.
    /// </summary>
    public bool HasTransition(string innerTerrainId, string outerTerrainId)
    {
        // Check direct key
        var key = CompiledTransitionMap.CreateKey(innerTerrainId, outerTerrainId);
        if (_transitionMap.Transitions.ContainsKey(key))
            return true;

        // Check border tile ID format
        var borderId = $"{innerTerrainId}_border";
        var borderKey = CompiledTransitionMap.CreateKey(borderId, outerTerrainId);
        return _transitionMap.Transitions.ContainsKey(borderKey);
    }

    /// <summary>
    /// Finds the solid fill for a terrain by looking up ANY transition with it.
    /// For inner terrains (auto-tiles), returns bitmask 15 (all corners filled).
    /// For outer terrains (base tiles), returns bitmask 0 (pure background).
    /// </summary>
    public Vector2I? ResolveSolidFill(string terrainId)
    {
        // First try as inner terrain (foreground auto-tile solid fill - bitmask 15)
        var result = ResolveAnyVariant(terrainId, 15);
        if (result.HasValue)
        {
            return result;
        }

        // Also try as outer terrain with bitmask 0 (base tile solid fill)
        // This handles base tiles like base_grass1 which are only used as outer terrains
        result = ResolveAsOuterTerrain(terrainId, 0);
        if (result.HasValue)
        {
            return result;
        }

        return null;
    }

    /// <summary>
    /// Finds coords by looking up the terrain as the OUTER terrain in any transition.
    /// Used to find base tile solid fills (bitmask 0) when the tile is only used as background.
    /// </summary>
    public Vector2I? ResolveAsOuterTerrain(string terrainId, int bitmask)
    {
        if (bitmask < 0 || bitmask >= 16)
            return null;

        // Find any transition that uses this terrain as the outer (background) terrain
        foreach (var (key, entry) in _transitionMap.Transitions)
        {
            if (CompiledTransitionMap.ParseKey(key).OuterTerrain != terrainId)
                continue;

            var coords = FirstVariantCoords(entry, bitmask);
            if (coords.HasValue)
                return coords;
        }

        return null;
    }

    /// <summary>
    /// Enumerates all terrain transition pairs defined in the map.
    /// Returns (innerTerrain, outerTerrain) tuples for WFC adjacency rule extraction.
    /// </summary>
    public IEnumerable<(string innerTerrain, string outerTerrain)> GetAllTransitionPairs()
    {
        foreach (var key in _transitionMap.Transitions.Keys)
        {
            var parsed = CompiledTransitionMap.ParseKey(key);
            yield return (parsed.BorderId, parsed.OuterTerrain);
        }
    }

    /// <summary>
    /// Finds coords for a specific bitmask variant by looking up ANY transition with the given terrain.
    /// Used as fallback when direct transition lookup fails.
    /// </summary>
    public Vector2I? ResolveAnyVariant(string terrainId, int bitmask)
    {
        // Validate bitmask range
        if (bitmask < 0 || bitmask >= 16)
            return null;

        // Find any transition that uses this terrain as the inner (border) terrain
        foreach (var (key, entry) in _transitionMap.Transitions)
        {
            if (CompiledTransitionMap.ParseKey(key).BorderId != terrainId)
                continue;

            var coords = FirstVariantCoords(entry, bitmask);
            if (coords.HasValue)
                return coords;
        }

        return null;
    }

    private static Vector2I? FirstVariantCoords(TransitionEntry entry, int bitmask)
    {
        if (entry.Variants.Length <= bitmask)
            return null;

        var variants = entry.Variants[bitmask];
        if (variants == null || variants.Length == 0)
            return null;

        return new Vector2I(variants[0].X, variants[0].Y);
    }
}
