using System;
using System.IO;
using System.Text.Json;
using CardCleaner.Scripts.Core.Interfaces;
using Godot;

namespace CardCleaner.Scripts.Features.Worldgen.AutoTiling;

/// <summary>
/// Resolves terrain transitions using the compiled transition map.
/// Loads the transition_map.json generated by the atlas compiler
/// and provides O(1) lookups for terrain transition coordinates.
/// </summary>
public class CompiledTransitionResolver : ITransitionResolver
{
    private const string DefaultTransitionMapPath = "res://Data/CompiledAtlas/transition_map.json";
    private const int DefaultCompiledAtlasSourceId = 0;

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    private readonly CompiledTransitionMap _transitionMap;
    private readonly int _compiledAtlasSourceId;

    /// <summary>
    /// Gets the source ID for the compiled atlas.
    /// </summary>
    public int CompiledAtlasSourceId => _compiledAtlasSourceId;

    /// <summary>
    /// Creates a resolver with the default transition map path.
    /// </summary>
    public CompiledTransitionResolver() : this(DefaultTransitionMapPath, DefaultCompiledAtlasSourceId)
    {
    }

    /// <summary>
    /// Creates a resolver with a custom transition map path.
    /// </summary>
    /// <param name="transitionMapPath">Path to the transition_map.json file.</param>
    /// <param name="compiledAtlasSourceId">Source ID for the compiled atlas in the TileSet.</param>
    public CompiledTransitionResolver(string transitionMapPath, int compiledAtlasSourceId)
    {
        _compiledAtlasSourceId = compiledAtlasSourceId;
        _transitionMap = LoadTransitionMap(transitionMapPath);
    }

    /// <summary>
    /// Resolves the atlas coordinates for a terrain transition.
    /// </summary>
    public Vector2I? ResolveTransition(string innerTerrainId, string outerTerrainId, int bitmask)
    {
        // Try direct lookup first (for fixed transitions and composited tiles)
        var coords = _transitionMap.GetVariantCoords(innerTerrainId, outerTerrainId, bitmask);
        if (coords.HasValue)
            return coords;

        // Try with border tile ID format: "{inner}_border"
        var borderId = $"{innerTerrainId}_border";
        coords = _transitionMap.GetVariantCoords(borderId, outerTerrainId, bitmask);
        if (coords.HasValue)
            return coords;

        // No transition found
        return null;
    }

    /// <summary>
    /// Resolves a transition with full render info, including fallback to provided coordinates.
    /// </summary>
    public TransitionResolveResult ResolveWithFallback(
        string innerTerrainId,
        string outerTerrainId,
        int bitmask,
        int fallbackSourceId,
        Vector2I fallbackCoords)
    {
        // Try compiled transition map first
        var coords = ResolveTransition(innerTerrainId, outerTerrainId, bitmask);
        if (coords.HasValue)
            return new TransitionResolveResult(_compiledAtlasSourceId, coords.Value);

        // Fallback to the provided coordinates (typically from tile's auto-tile variants)
        return new TransitionResolveResult(fallbackSourceId, fallbackCoords);
    }

    /// <summary>
    /// Checks if a transition exists for the given terrain pair.
    /// </summary>
    public bool HasTransition(string innerTerrainId, string outerTerrainId)
    {
        // Check direct key
        var key = CompiledTransitionMap.CreateKey(innerTerrainId, outerTerrainId);
        if (_transitionMap.Transitions.ContainsKey(key))
            return true;

        // Check border tile ID format
        var borderId = $"{innerTerrainId}_border";
        var borderKey = CompiledTransitionMap.CreateKey(borderId, outerTerrainId);
        return _transitionMap.Transitions.ContainsKey(borderKey);
    }

    /// <summary>
    /// Finds the solid fill (bitmask 15) for a terrain by looking up ANY transition with it.
    /// Used for uniform terrain where self-transitions don't exist.
    /// </summary>
    public Vector2I? ResolveSolidFill(string terrainId)
    {
        // Find any transition that uses this terrain as the inner (border) terrain
        // At bitmask 15, the border completely covers the base, giving us the solid fill
        foreach (var (key, entry) in _transitionMap.Transitions)
        {
            var (borderId, _) = CompiledTransitionMap.ParseKey(key);
            if (borderId == terrainId && entry.Variants.Length > 15 && entry.Variants[15] != null)
            {
                var v = entry.Variants[15];
                return new Vector2I(v.X, v.Y);
            }
        }

        return null;
    }

    private static CompiledTransitionMap LoadTransitionMap(string path)
    {
        try
        {
            var absolutePath = ProjectSettings.GlobalizePath(path);
            if (!File.Exists(absolutePath))
            {
                ILog.Print($"[CompiledTransitionResolver] Transition map not found: {absolutePath}");
                return new CompiledTransitionMap();
            }

            var json = File.ReadAllText(absolutePath);
            var map = JsonSerializer.Deserialize<CompiledTransitionMap>(json, JsonOptions);

            if (map == null)
            {
                ILog.Print("[CompiledTransitionResolver] Failed to deserialize transition map");
                return new CompiledTransitionMap();
            }

            ILog.Print($"[CompiledTransitionResolver] Loaded {map.Transitions.Count} transitions from {path}");
            return map;
        }
        catch (Exception ex)
        {
            ILog.Print($"[CompiledTransitionResolver] Error loading transition map: {ex.Message}");
            return new CompiledTransitionMap();
        }
    }
}
