using System.Collections.Generic;
using CardCleaner.Scripts.Core.DependencyInjection;
using CardCleaner.Scripts.Core.Interfaces;
using CardCleaner.Scripts.Features.Deckbuilder.Tiles;
using Godot;

namespace CardCleaner.Scripts.Features.Deckbuilder.Services;

/// <summary>
/// Simple map data structure using tile IDs
/// </summary>
public class SimpleMapData
{
    private ITileRegistry? _tileRegistry;
    private HashSet<Vector2I>? _passableTilesSet;
    public string[,] TileIds { get; set; } = new string[0, 0];

    /// <summary>
    /// Background terrain generated by WFC phase 1 for dual-grid rendering.
    /// </summary>
    public string[,]? BackgroundLayer { get; set; }

    /// <summary>
    /// Foreground auto-tile terrain generated by WFC phase 2 for dual-grid rendering.
    /// </summary>
    public string[,]? ForegroundLayer { get; set; }

    public string[,]? BiomeMap { get; set; }
    public Vector2I Size { get; set; }
    public Vector2I PlayerStart { get; set; }
    public List<Vector2I> EnemyPositions { get; set; } = new();
    public List<Vector2I> PassableTiles { get; set; } = new();

    /// <summary>
    /// Pre-selected variation indices for tiles using VariationMode.PerGeneration.
    /// </summary>
    public Dictionary<string, int> PerGenerationVariants { get; set; } = new();

    /// <summary>
    /// Pre-selected tile IDs for variation groups using PerGeneration mode.
    /// </summary>
    public Dictionary<string, string> PerGenerationGroupVariants { get; set; } = new();

    /// <summary>
    /// Context-selected variation indices for tiles using VariationMode.Contextual.
    /// </summary>
    public Dictionary<Vector2I, int> ContextualVariants { get; set; } = new();

    /// <summary>
    /// Dual-grid terrain data mapping visual positions to base/top IDs and Corner16 bitmasks.
    /// </summary>
    public Dictionary<Vector2I, (string BaseTileId, string TopTileId, int Bitmask)>
        DecorationOverlays { get; set; } = new();

    /// <summary>
    /// Whether decoration overlays use half-tile dual-grid positioning.
    /// </summary>
    public bool UsesDualGridOverlays { get; set; } = true;

    public string GetBiomeAt(Vector2I pos)
    {
        if (BiomeMap == null || !IsInBounds(pos))
            return "plains";
        return BiomeMap[pos.Y, pos.X];
    }

    public bool IsPassable(Vector2I pos)
    {
        if (!IsInBounds(pos))
            return false;

        // Use PassableTiles as primary source (set during map generation)
        if (PassableTiles.Count > 0)
            return PassableTilesSet.Contains(pos);

        // Fallback to tile registry lookup
        var tile = LookupTile(pos);
        return tile?.IsPassable ?? false;
    }

    public bool IsTransparent(Vector2I pos)
    {
        if (!IsInBounds(pos))
            return false;

        // Use PassableTiles as primary source (set during map generation)
        // Most passable tiles are also transparent
        if (PassableTiles.Count > 0 && PassableTilesSet.Contains(pos))
            return true;

        var tile = LookupTile(pos);
        return tile?.IsTransparent ?? false;
    }

    private bool IsInBounds(Vector2I pos)
    {
        return pos.X >= 0 && pos.X < Size.X && pos.Y >= 0 && pos.Y < Size.Y;
    }

    private HashSet<Vector2I> PassableTilesSet => _passableTilesSet ??= new HashSet<Vector2I>(PassableTiles);

    /// <summary>
    /// Looks up the registry tile for an in-bounds position.
    /// Returns null when the registry is unavailable, so callers default to false.
    /// </summary>
    private TileDefinition? LookupTile(Vector2I pos)
    {
        _tileRegistry ??= ServiceLocator.Has<ITileRegistry>() ? ServiceLocator.Get<ITileRegistry>() : null;
        return _tileRegistry?.GetTile(TileIds[pos.Y, pos.X]);
    }

    /// <summary>
    /// Gets the tile ID at a position. Returns empty string for out-of-bounds positions.
    /// </summary>
    public string GetTileId(Vector2I pos)
    {
        if (!IsInBounds(pos))
            return string.Empty;
        return TileIds[pos.Y, pos.X];
    }

    /// <summary>
    /// Cache of terrain positions that are covered by edge tile overlays.
    /// Used to prevent other decorations from spawning at these positions.
    /// </summary>
    private HashSet<Vector2I>? _edgeTileCoverage;

    /// <summary>
    /// Check if a terrain position is covered by an edge tile overlay.
    /// With dual-grid overlays, a visual tile at (vx, vy) covers terrain cells
    /// at its 4 corners: (vx-1, vy-1), (vx, vy-1), (vx-1, vy), (vx, vy).
    /// </summary>
    public bool HasEdgeTileOverlay(Vector2I terrainPos)
    {
        if (DecorationOverlays.Count == 0)
            return false;

        // Build cache on first access
        if (_edgeTileCoverage == null)
        {
            _edgeTileCoverage = new HashSet<Vector2I>();

            foreach (var (visualPos, (_, _, bitmask)) in DecorationOverlays)
            {
                // Only count positions with actual transitions (not 0 or 15)
                // Note: 15 = all corners filled in Corner16 format (NE=1 + SE=2 + SW=4 + NW=8)
                if (bitmask == 0 || bitmask == 15)
                    continue;

                // Visual tile at (vx, vy) covers terrain cells at its 4 corners
                // TL corner: (vx-1, vy-1)
                // TR corner: (vx, vy-1)
                // BL corner: (vx-1, vy)
                // BR corner: (vx, vy)
                if (UsesDualGridOverlays)
                {
                    _edgeTileCoverage.Add(new Vector2I(visualPos.X - 1, visualPos.Y - 1));
                    _edgeTileCoverage.Add(new Vector2I(visualPos.X, visualPos.Y - 1));
                    _edgeTileCoverage.Add(new Vector2I(visualPos.X - 1, visualPos.Y));
                    _edgeTileCoverage.Add(new Vector2I(visualPos.X, visualPos.Y));
                }
                else
                {
                    // Legacy non-dual-grid: position is terrain position
                    _edgeTileCoverage.Add(visualPos);
                }
            }
        }

        return _edgeTileCoverage.Contains(terrainPos);
    }

    /// <summary>
    /// Get all terrain positions that should block other decorations
    /// due to edge tile overlays.
    /// </summary>
    public IReadOnlySet<Vector2I> GetEdgeTileCoverage()
    {
        // Ensure cache is built
        if (_edgeTileCoverage == null)
        {
            HasEdgeTileOverlay(Vector2I.Zero); // Triggers cache build
        }
        return _edgeTileCoverage ?? new HashSet<Vector2I>();
    }

    /// <summary>
    /// Clear the edge tile coverage cache (call when DecorationOverlays changes).
    /// </summary>
    public void InvalidateEdgeTileCache()
    {
        _edgeTileCoverage = null;
    }
}
