using System.Collections.Generic;
using CardCleaner.Scripts.Core.DependencyInjection;
using CardCleaner.Scripts.Core.Interfaces;
using Godot;

namespace CardCleaner.Scripts.Features.Deckbuilder.Services;

/// <summary>
/// Simple map data structure using tile IDs
/// </summary>
public class SimpleMapData
{
    private ITileRegistry? _tileRegistry;
    private HashSet<Vector2I>? _passableTilesSet;
    public string[,] TileIds { get; set; } = new string[0, 0];

    /// <summary>
    /// Background layer containing only simple (non-auto-tile) terrain.
    /// Generated by WFC phase 1. Used as base in dual-grid rendering.
    /// </summary>
    public string[,]? BackgroundLayer { get; set; }

    /// <summary>
    /// Foreground layer containing only auto-tile terrain.
    /// Generated by WFC phase 2 with gap constraint.
    /// Used as top layer in dual-grid rendering.
    /// </summary>
    public string[,]? ForegroundLayer { get; set; }

    public string[,]? BiomeMap { get; set; }
    public Vector2I Size { get; set; }
    public Vector2I PlayerStart { get; set; }
    public List<Vector2I> EnemyPositions { get; set; } = new();
    public List<Vector2I> PassableTiles { get; set; } = new();

    /// <summary>
    /// Pre-selected variation indices for tiles with VariationMode.PerGeneration.
    /// Maps tile ID to the selected variation index (0-based into TileDefinition.Variations).
    /// </summary>
    public Dictionary<string, int> PerGenerationVariants { get; set; } = new();

    /// <summary>
    /// Pre-selected tile IDs for variation groups with PerGeneration mode.
    /// Maps group base name (e.g., "grass") to the selected tile ID (e.g., "grass2").
    /// When rendering, tiles in these groups should use the selected variant.
    /// </summary>
    public Dictionary<string, string> PerGenerationGroupVariants { get; set; } = new();

    /// <summary>
    /// Context-selected variation indices for tiles with VariationMode.Contextual.
    /// Maps tile position to variation index (0-based into TileDefinition.Variations).
    /// Variants are selected based on biome, nearby tiles, and other context.
    /// </summary>
    public Dictionary<Vector2I, int> ContextualVariants { get; set; } = new();

    /// <summary>
    /// Dual-grid terrain data for proper base + top layer rendering.
    /// Maps visual grid position to (baseTileId, topTileId, bitmask) for dual-layer rendering.
    /// Visual grid is (Size.X+1, Size.Y+1) and offset by half a tile from terrain grid.
    /// Base terrain fills background, top terrain uses Corner16 auto-tiling.
    /// Bitmask of 15 (all corners) indicates no transition at this position.
    /// </summary>
    public Dictionary<Vector2I, (string BaseTileId, string TopTileId, int Bitmask)> DecorationOverlays { get; set; } = new();

    /// <summary>
    /// Whether decoration overlays use dual-grid positioning (half-tile offset).
    /// When true, overlay positions are visual grid coordinates that need to be
    /// rendered at (-0.5, -0.5) tile offset from the terrain grid.
    /// </summary>
    public bool UsesDualGridOverlays { get; set; } = true;

    public string GetBiomeAt(Vector2I pos)
    {
        if (BiomeMap == null || pos.X < 0 || pos.X >= Size.X || pos.Y < 0 || pos.Y >= Size.Y)
            return "plains";
        return BiomeMap[pos.Y, pos.X];
    }

    public bool IsPassable(Vector2I pos)
    {
        if (pos.X < 0 || pos.X >= Size.X || pos.Y < 0 || pos.Y >= Size.Y)
            return false;

        // Use PassableTiles as primary source (set during map generation)
        if (PassableTiles.Count > 0)
        {
            _passableTilesSet ??= new HashSet<Vector2I>(PassableTiles);
            return _passableTilesSet.Contains(pos);
        }

        // Fallback to tile registry lookup
        var tileId = TileIds[pos.Y, pos.X];
        _tileRegistry ??= ServiceLocator.Has<ITileRegistry>() ? ServiceLocator.Get<ITileRegistry>() : null;

        if (_tileRegistry == null)
        {
            // Registry unavailable - cannot determine passability, default to false
            return false;
        }

        var tile = _tileRegistry.GetTile(tileId);
        return tile?.IsPassable ?? false;
    }

    public bool IsTransparent(Vector2I pos)
    {
        if (pos.X < 0 || pos.X >= Size.X || pos.Y < 0 || pos.Y >= Size.Y)
            return false;

        var tileId = TileIds[pos.Y, pos.X];

        // Use PassableTiles as primary source (set during map generation)
        // Most passable tiles are also transparent
        if (PassableTiles.Count > 0)
        {
            _passableTilesSet ??= new HashSet<Vector2I>(PassableTiles);
            if (_passableTilesSet.Contains(pos))
                return true;
        }

        _tileRegistry ??= ServiceLocator.Has<ITileRegistry>() ? ServiceLocator.Get<ITileRegistry>() : null;

        if (_tileRegistry == null)
        {
            // Registry unavailable - cannot determine transparency, default to false
            return false;
        }

        var tile = _tileRegistry.GetTile(tileId);
        return tile?.IsTransparent ?? false;
    }

    /// <summary>
    /// Gets the tile ID at a position. Returns empty string for out-of-bounds positions.
    /// </summary>
    public string GetTileId(Vector2I pos)
    {
        if (pos.X < 0 || pos.X >= Size.X || pos.Y < 0 || pos.Y >= Size.Y)
            return string.Empty;
        return TileIds[pos.Y, pos.X];
    }

    /// <summary>
    /// Cache of terrain positions that are covered by edge tile overlays.
    /// Used to prevent other decorations from spawning at these positions.
    /// </summary>
    private HashSet<Vector2I>? _edgeTileCoverage;

    /// <summary>
    /// Check if a terrain position is covered by an edge tile overlay.
    /// With dual-grid overlays, a visual tile at (vx, vy) covers terrain cells
    /// at its 4 corners: (vx-1, vy-1), (vx, vy-1), (vx-1, vy), (vx, vy).
    /// </summary>
    public bool HasEdgeTileOverlay(Vector2I terrainPos)
    {
        if (DecorationOverlays.Count == 0)
            return false;

        // Build cache on first access
        if (_edgeTileCoverage == null)
        {
            _edgeTileCoverage = new HashSet<Vector2I>();

            foreach (var (visualPos, (_, _, bitmask)) in DecorationOverlays)
            {
                // Only count positions with actual transitions (not 0 or 15)
                // Note: 15 = all corners filled in Corner16 format (NE=1 + SE=2 + SW=4 + NW=8)
                if (bitmask == 0 || bitmask == 15)
                    continue;

                // Visual tile at (vx, vy) covers terrain cells at its 4 corners
                // TL corner: (vx-1, vy-1)
                // TR corner: (vx, vy-1)
                // BL corner: (vx-1, vy)
                // BR corner: (vx, vy)
                if (UsesDualGridOverlays)
                {
                    _edgeTileCoverage.Add(new Vector2I(visualPos.X - 1, visualPos.Y - 1));
                    _edgeTileCoverage.Add(new Vector2I(visualPos.X, visualPos.Y - 1));
                    _edgeTileCoverage.Add(new Vector2I(visualPos.X - 1, visualPos.Y));
                    _edgeTileCoverage.Add(new Vector2I(visualPos.X, visualPos.Y));
                }
                else
                {
                    // Legacy non-dual-grid: position is terrain position
                    _edgeTileCoverage.Add(visualPos);
                }
            }
        }

        return _edgeTileCoverage.Contains(terrainPos);
    }

    /// <summary>
    /// Get all terrain positions that should block other decorations
    /// due to edge tile overlays.
    /// </summary>
    public IReadOnlySet<Vector2I> GetEdgeTileCoverage()
    {
        // Ensure cache is built
        if (_edgeTileCoverage == null)
        {
            HasEdgeTileOverlay(Vector2I.Zero); // Triggers cache build
        }
        return _edgeTileCoverage ?? new HashSet<Vector2I>();
    }

    /// <summary>
    /// Clear the edge tile coverage cache (call when DecorationOverlays changes).
    /// </summary>
    public void InvalidateEdgeTileCache()
    {
        _edgeTileCoverage = null;
    }
}
